#!/usr/bin/env python3

import rospy
from geometry_msgs.msg import Twist, Pose
from std_msgs.msg import Int32

import time  # Import the Time library
from gpiozero import CamJamKitRobot  # Import the CamJam GPIO Zero Library
from gpiozero import Robot, RotaryEncoder

def _clip(value, minimum, maximum):
    """Ensure value is between minimum and maximum."""

    if value < minimum:
        return minimum
    elif value > maximum:
        return maximum
    return value


class Driver:
    def __init__(self):
        rospy.init_node('driver')
        self.nodename = rospy.get_name()
        rospy.loginfo("-I- %s started" % self.nodename)

        self._last_received = rospy.get_time()
        self._timeout = rospy.get_param('~timeout', 2)
        self._rate = rospy.get_param('~rate', 5)
        self._max_speed = rospy.get_param('~max_speed', 0.5)
        self._wheel_base = rospy.get_param('~wheel_base', 0.155)

        self._robot = CamJamKitRobot()

        self._left_encoder = RotaryEncoder(18,17,max_steps=0)
        self._right_encoder = RotaryEncoder(22,23,max_steps=0)

#TUNE BETTER
        self.KP = 0.25
        self.KD = 0.125
        self.KI = 0.0375

        self._left_speed = 0
        self._right_speed = 0

        self._left_speed_target = 0
        self._right_speed_target = 0

        self.l_prev_error = 0
        self.r_prev_error = 0

        self.l_sum_error = 0
        self.r_sum_error = 0
        
        # Setup subscriber for velocity twist message
        rospy.Subscriber(
            'cmd_vel', Twist, self.velocity_received_callback)
        
        self.leftPub = rospy.Publisher('~lwheel_ticks',
                                       Int32, queue_size=10)
        self.rightPub = rospy.Publisher('~rwheel_ticks',
                                        Int32, queue_size=10)

    def velocity_received_callback(self, message):
        """Handle new velocity command message."""

        self._last_received = rospy.get_time()

        # Extract linear and angular velocities from the message
        linear = message.linear.x
        angular = message.angular.z

        # Calculate wheel speeds in m/s
        self._left_speed_target = linear - angular*self._wheel_base/2
        self._right_speed_target = linear + angular*self._wheel_base/2


    def run(self):
        """The control loop of the driver."""

        rate = rospy.Rate(self._rate)

        self.nodeName = rospy.get_name()
        rospy.loginfo("{0} started".format(self.nodeName))

        while not rospy.is_shutdown():
            left_speed_actual = self._left_encoder.steps*0.005625*self._rate
            right_speed_actual = self._right_encoder.steps*0.005625*self._rate
            l_error = self._left_speed_target - left_speed_actual 
            r_error = self._right_speed_target - right_speed_actual

            self._left_speed += l_error * self.KP + (self.l_prev_error * self.KD) + (self.l_sum_error * self.KI)
            self._right_speed += r_error * self.KP + (self.r_prev_error * self.KD) + (self.r_sum_error * self.KI)
#overide PID for testing
            self._left_speed = self._left_speed_target*4
            self._right_speed = self._right_speed_target*4

            self._left_speed = max(min(1, self._left_speed), -1)
            self._right_speed = max(min(1, self._right_speed), -1)

            # If we haven't received new commands for a while, we
            # may have lost contact with the commander-- stop
            # moving
            delay = rospy.get_time() - self._last_received
            if delay < self._timeout:
                if (abs(self._left_speed) > 0.15) and (self._left_speed_target != 0):
                    if self._left_speed > 0:
                        self._robot.left_motor.forward(abs(self._left_speed))
                    else:
                        self._robot.left_motor.backward(abs(self._left_speed))
                else:
                    self._robot.left_motor.stop()
                    if self._left_speed_target == 0:
                        self._left_speed = 0
                        self.l_error = 0
                        self.l_prev_error = 0
                        self.l_sum_error = 0

                if(abs(self.l_sum_error) > abs(1000*self._left_speed)):
                    rospy.logwarn("Drastic l_sum_error. Could be a collision")
                        
                if (abs(self._right_speed) > 0.15) and (self._right_speed_target != 0):
                    if self._right_speed > 0:
                        self._robot.right_motor.forward(abs(self._right_speed))
                    else:
                        self._robot.right_motor.backward(abs(self._right_speed))
                else:
                    self._robot.right_motor.stop()
                    if self._right_speed_target == 0:
                        self._right_speed = 0
                        self.r_error = 0
                        self.r_prev_error = 0
                        self.r_sum_error = 0

                if(abs(self.r_sum_error) > abs(1000*self._right_speed)):
                    rospy.logwarn("Drastic r_sum_error. Could be a collision")
 
            else:
                self._robot.stop()

            self.leftPub.publish(self._left_encoder.steps)
            self.rightPub.publish(self._right_encoder.steps)

            print("L Target {: 0.2f} L Actual {: 0.2f} L Power {: 0.2f} L Encoder {: 0.2f} L Error {: 0.2f} L Prev_Error {: 0.2f} L Sum_Error {: 0.2f}".format(self._left_speed_target, left_speed_actual, self._left_speed, self._left_encoder.steps, l_error, self.l_prev_error, self.l_sum_error))
            print("R Target {: 0.2f} R Actual {: 0.2f} R Power {: 0.2f} R Encoder {: 0.2f} R Error {: 0.2f} R Prev_Error {: 0.2f} R Sum_Error {: 0.2f}".format(self._right_speed_target, right_speed_actual, self._right_speed, self._right_encoder.steps, r_error, self.r_prev_error, self.r_sum_error))

            self._left_encoder.steps = 0
            self._right_encoder.steps = 0

            self.l_prev_error = l_error
            self.r_prev_error = r_error

            self.l_sum_error += l_error
            self.r_sum_error += r_error

            rate.sleep()


def main():
    driver = Driver()

    # Run driver. This will block
    driver.run()

if __name__ == '__main__':
    main()
